apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    app: mongodb
    project: roboshop
    tier: db
spec:
  clusterIP: None
  selector:
     app: mongodb
     project: roboshop
     tier: db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017